# Site settings
title: Erik Wahlberger - Portfolio
description: A website containing my software development portfolio
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Erik Wahlberger
user_description: |
  A software developer from Sweden, with a passion for adventures, technology, photography and music production. Started to learn software development as a hobby during 2008. Ever since, I have developed this skill by using self-developed software to solve everyday problems, especially related to self-hosting services, which is something that I do. Examples of such projects can be found below.
user_title: Software Developer
email: erik@wahlberger.dev
linkedin_username: erikwahlberger
github_username: Erik142

# Google-analytics
google-analytics:
  id: ""

exclude: ["package.json", "src", "node_modules"]
